/*
        [BottleId]      INT IDENTITY (1,1) PRIMARY KEY NOT NULL ,
        [Name]          VARCHAR(255) NOT NULL ,
        [ReleaseTypeId] INT NOT NULL ,
        [DistilleryId]  INT NOT NULL ,
        [Proof]         DECIMAL(18,2) NOT NULL ,
        [AgeYears]      INT NOT NULL ,
        [AgeMonths]     INT NOT NULL ,
        [AgeDays]       INT NOT NULL 
*/
DECLARE @BourbonTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'BOURBON')
DECLARE @RyeTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'RYE')
DECLARE @LightTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'LIGHT')
DECLARE @AmericanTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'AMERICAN')
DECLARE @BouryeTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'BOURYE')
DECLARE @CanadianTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'CANADIAN')
DECLARE @TennesseeTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'TENNESSEE')
DECLARE @SmsTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'SMS')
DECLARE @AmsTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'AMS')
DECLARE @WheatTypeId INT = (SELECT [WhiskeyTypeId] FROM [WhiskeyTypes] WHERE [Code] = 'WHEAT')


--INSERT INTO [Bottles] ([Name], [ReleaseTypeId], [DistilleryId], [Proof], [AgeYears], [AgeMonths], [AgeDays]) VALUES

DROP TABLE IF EXISTS #TempBottles 

SELECT * INTO #TempBottles FROM
(
    VALUES 
    ('Heaven Hill', 'Elijah Craig Barrel Proof','', '', '', '', 'Bourbon', 'Small Batch', 'B521', '12y', '118.2', '', '2'),
    ('Heaven Hill', 'Elijah Craig Barrel Proof','', '', '', '', 'Bourbon', 'Small Batch', 'B523', '11y5m', '124.2', '', '2'),
    ('Heaven Hill', 'Elijah Craig Barrel Proof','', '', '', '', 'Bourbon', 'Small Batch', 'A121', '12y', '123.6', '', '1'),
    ('Heaven Hill', 'Elijah Craig Barrel Proof','', '', '', '', 'Bourbon', 'Small Batch', 'A123', '12y', '125.6', '', '1'),
    ('Heaven Hill', 'Elijah Craig Barrel Proof','6327714', 'BHG #256', '', '', 'Bourbon', 'Single Barrel', '', '9y', '128.7', '', '1'),
    ('Heaven Hill', 'Larceny Barrel Proof','', '', '', '', 'Bourbon', 'Small Batch', 'C923', '', '126.4', '', '2'),
    ('Cat''s Eye Distillery', 'Obtainium','SC-00164', '', '', '', 'Light Whiskey', 'Single Barrel', '', '16y', '140.2', '', '0'),
    ('Calumet Farm', 'Single Rack Black','', '', 'U3609.09', '', 'Bourbon', 'Small Batch', '', '15y', '105', '', '1'),
    ('Wild Turkey', 'Russel''s Reserve','', 'Cox''s & Evergreen 2022 #2', 'A', '5', 'Bourbon', 'Single Barrel', '', '9y', '110', '', '1'),
    ('Wild Turkey', 'Russel''s Reserve','', 'Total Wine & More', 'A', '4', 'Bourbon', 'Single Barrel', '', '9y10m', '110', '', '1'),
    ('Jack Daniel''s', 'Jack Daniel''s Barrel Proof ','19-15055', 'The Party Source', 'R-22', '', 'Tennessee Whiskey', 'Single Barrel', '', '', '129.6', '', '1'),
    ('Jack Daniel''s', 'Jack Daniel''s Barrel Proof ','23-06042', '', '45357', '', 'Tennessee Whiskey', 'Single Barrel', '', '', '130.7', '', '1'),
    ('Angel''s Envy', 'Angel''s Envy','', '', '', '', 'Bourbon', 'Small Batch', '69E', '', '86.6', 'Port Wine Barrel', '1'),
    ('Angel''s Envy', 'Angel''s Envy Private Selection','JB-230835', 'Rule #1', '', '', 'Bourbon', 'Single Barrel', '', '', '109', 'Port Wine Barrel', '1'),
    ('Angel''s Envy', 'Angel''s Envy Private Selection','JB-2879C', 'OHLQ', '', '', 'Bourbon', 'Single Barrel', '', '', '102.7', 'Port Wine Barrel', '1'),
    ('Bull Run', 'American Whiskey','', '', '', '', 'American Whiskey', 'Small Batch', 'APF42OR', '12y', '123.1', 'Pinot Noir Casks', '1'),
    ('Bull Run', 'Straight Bourbon Whiskey','', 'Total Wine & More', '', '', 'Bourbon', 'Single Barrel', '', '12y', '125.6', 'Cognac Casks', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', 'Federal Grill', 'B', '5', 'Bourbon', 'Single Barrel', '', '', '134.2', '', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', 'Shovel City and Opa', 'G', '7', 'Bourbon', 'Single Barrel', '', '', '128.7', '', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', 'Remember, Remember', 'I', '4', 'Bourbon', 'Single Barrel', '', '', '130.6', '', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', '', 'K', '3', 'Bourbon', 'Single Barrel', '', '', '133.6', '', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', 'Helluvator', 'H', '4', 'Bourbon', 'Single Barrel', '', '', '127', '', '1'),
    ('Augusta', 'Buckner''s Single Barrel','', '', '', '', 'Bourbon', 'Single Barrel', '', '10y', '124', '', '1'),
    ('2XO', 'The Tribute Blend','', '', '', '', 'Bourbon', 'Small Batch', '', '', '104', 'Double Oak', '1'),
    ('Nashville Barrel Company', 'Single Barrel Straight Bourbon Whiskey','2768', '', '', '', 'Bourbon', 'Single Barrel', '', '8y', '122.48', '', '1'),
    ('Jersey Artisan Distilling', 'Barrel Bandit','11', '', '', '', 'Rye', 'Single Barrel', '', '8y', '114.4', '', '1'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','18', 'Dream Team ''20', '', '', 'Rye', 'Single Barrel', '', '7y', '113.46', '', '1'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','80', 'Minnesota Whiskey Society', '', '', 'Rye', 'Single Barrel', '', '7y', '115.44', '', '1'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','29', 'R/Bourbon Single Barrel Selection', '', '', 'Rye', 'Single Barrel', '', '8y', '108.46', '', '1'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','32', 'Order of the Robe', '', '', 'Rye', 'Single Barrel', '', '7y', '114.78', '', '1'),
    ('Heaven Hill', 'Pikesville','', '', '', '', 'Rye', 'Small Batch', '', '6y', '110', '', '1'),
    ('Sagamore Spirits', '8 Year Old Rye','', '', '', '', 'Rye', 'Small Batch', '', '8y', '114.9', '', '1'),
    ('Middle West Spirits', 'Dark Pumpernickel Rye','216', '', '', '', 'Rye', 'Single Barrel', '', '6y', '129.9', '', '1'),
    ('Proof & Wood Ventures', 'The Cabinet','', '', '', '', 'Bourye', 'Small Batch', '', '4y', '112.48', '', '1'),
    ('Traverse City Whiskey Co.', 'Straight Bourbon Whiskey','', '', '', '', 'Bourbon', 'Small Batch', '', '', '118.4', '', '1'),
    ('Triple Down', 'Light Whiskey','', 'Happy Cloud - Edition 1', '', '', 'Light Whiskey', 'Single Barrel', '', '', '142', '', '1'),
    ('Early Times', 'Early Times','', '', '', '', 'Bourbon', 'Small Batch', '', '4y', '100', '', '2'),
    ('Cat''s Eye Distillery', 'Obtainium','SC-00330', 'Flask Fine Wine & Whisky', '', '', 'Canadian Whiskey', 'Single Barrel', '', '26y', '154.6', '', '1'),
    ('Tincup', 'Fourteener','', '', '', '', 'Bourbon', 'Small Batch', '', '14y', '84', '', '1'),
    ('Tincup', 'Tincup 10','', '', '', '', 'Bourbon', 'Small Batch', '', '10y', '84', '', '1'),
    ('Holladay Distillery', 'Soft Red Wheat Bottled-In-Bond','', '', '', '', 'Bourbon', 'Small Batch', '', '6y', '100', '', '1'),
    ('Whiskey Theif Distillery', 'Kentucky Straight Bourbon','', '', '', '', 'Bourbon', 'Single Barrel', '', '7y', '120.8', '', '1'),
    ('Buffalo Trace Distillery', 'Blanton''s','', '', 'H', '', 'Bourbon', 'Single Barrel', '', '', '93', '', '1'),
    ('Lux Row', 'Rebel 10 Year Single Barrel','5726977', '', '', '', 'Bourbon', 'Single Barrel', '', '10y', '100', '', '1'),
    ('Bardstown Bourbon Company', 'Discovery Series','', '', '', '', 'Bourbon', 'Small Batch', 'Batch 8', '6y', '114.1', '', '1'),
    ('Four Roses', 'Four Roses Single Barrel Private Select','71-2P', '', 'RS', '', 'Bourbon', 'Single Barrel', '', '9y8m', '113.4', '', '1'),
    ('Four Roses', 'Four Roses Single Barrel Private Select','21-2B', '', 'TN', '', 'Bourbon', 'Single Barrel', '', '10y2m', '114.2', '', '1'),
    ('Four Roses', 'Four Roses Single Barrel Private Select','24-4B', '', 'RS', '', 'Bourbon', 'Single Barrel', '', '10y9m', '122.6', '', '1'),
    ('Buffalo Trace Distillery', 'Weller Antique 107','', '', '', '', 'Bourbon', 'Small Batch', '', '', '107', '', '2'),
    ('Penelope', 'Barrel Strength Private Select','', '', '', '', 'Bourbon', 'Small Batch', '23-202', '9y', '109', '', '1'),
    ('Blackout Group', 'American Straight Whiskey','', '', '', '', 'American Whiskey', 'Small Batch', '1', '17y', '136.6', '', '1'),
    ('High West', 'Bourye','', '', '', '', 'Bourye', 'Small Batch', '23A26', '', '92', '', '1'),
    ('Buffalo Trace Distillery', 'William Larue Weller','', '', '', '', 'Bourbon', 'Small Batch', '2022', '12y', '124.7', '', '1'),
    ('Four Roses', 'Limited Edition Barrel Strength','', '', '', '', 'Bourbon', 'Small Batch', '2021', '', '114.2', '', '1'),
    ('Buffalo Trace Distillery', 'Colonel E.H. Taylor Small Batch','', '', '', '', 'Bourbon', 'Small Batch', '', '', '100', '', '2'),
    ('Buffalo Trace Distillery', 'Weller Full Proof','', '', '', '', 'Bourbon', 'Small Batch', '', '', '114', '', '1'),
    ('Blaum Bros', 'Oldfangled Knotter Bourbon','', '', '', '', 'Bourbon', 'Single Barrel', '', '12y', '106.4', '', '1'),
    ('Wild Turkey', 'Master''s Keep 17 Year Bottled In Bond','', '', '', '', 'Bourbon', 'Small Batch', '', '17y', '100', '', '1'),
    ('Buffalo Trace Distillery', 'Stagg Jr','', 'Bourbon St Wine and Spirits Selection 1', '', '', 'Bourbon', 'Single Barrel', '', '', '133.9', '', '1'),
    ('Buffalo Trace Distillery', 'Stagg Jr','', '', '', '', 'Bourbon', 'Small Batch', 'Batch 13', '', '128.4', '', '1'),
    ('Buffalo Trace Distillery', 'Stagg Jr','', '', '', '', 'Bourbon', 'Small Batch', 'Batch 14', '', '130.2', '', '1'),
    ('Buffalo Trace Distillery', 'Stagg Jr','', '', '', '', 'Bourbon', 'Small Batch', 'Batch 15', '', '131.1', '', '2'),
    ('Buffalo Trace Distillery', 'Stagg Jr','', '', '', '', 'Bourbon', 'Small Batch', 'Batch 17', '', '128.7', '', '1'),
    ('Orphan Barrel', 'Rhetoric 20','', '', '', '', 'Bourbon', 'Small Batch', '', '20y', '90', '', '1'),
    ('Orphan Barrel', 'Rhetoric 21','', '', '', '', 'Bourbon', 'Small Batch', '', '21y', '90.2', '', '1'),
    ('Orphan Barrel', 'Rhetoric 24','', '', '', '', 'Bourbon', 'Small Batch', '', '24y', '90.8', '', '2'),
    ('Orphan Barrel', 'Rhetoric 25','', '', '', '', 'Bourbon', 'Small Batch', '', '25y', '91', '', '1'),
    ('Sixth Street', 'Rye Whiskey','', 'Liquor Depot', '', '', 'Rye', 'Single Barrel', '', '8y', '120', '', '1'),
    ('Sixth Street', 'Bourbon','', '', '', '', 'Bourbon', 'Single Barrel', '', '12y', '100', '', '1'),
    ('Buffalo Trace Distillery', 'Colonel E.H. Taylor Single Barrel','', '', '', '', 'Bourbon', 'Single Barrel', '', '', '100', '', '1'),
    ('Buffalo Trace Distillery', 'Colonel E.H. Taylor Rye','', '', '', '', 'Rye', 'Small Batch', '', '', '100', '', '1'),
    ('Buffalo Trace Distillery', 'Colonel E.H. Taylor Warehouse C','', '', '', '', 'Bourbon', 'Small Batch', '', '', '100', '', '1'),
    ('Woodford Reserve', 'Batch Proof','', '', '', '', 'Bourbon', 'Small Batch', '', '', '124.7', '', '1'),
    ('Middle West Spirits', 'Ported Pumpernickel Rye','', '', '', '', 'Rye', 'Small Batch', '', '5y', '99.5', 'French Tawny Port Casks', '1'),
    ('Old Forester', 'Single Barrel Barrel Strength Rye','', '', 'K', '2', 'Rye', 'Single Barrel', '', '', '130.9', '', '1'),
    ('Old Forester', 'Single Barrel Barrel Strength Rye','', '', 'K', '2', 'Rye', 'Single Barrel', '', '', '131.9', '', '1'),
    ('Watershed', 'Single Barrel Bourbon','577', 'Who''s Your Daddy', '', '', 'Bourbon', 'Single Barrel', '', '4y', '121.4', '', '1'),
    ('Jack Daniel''s', 'Jack Daniel''s Distillery Series','', '', '', '', 'Tennessee Whiskey', 'Small Batch', '', '', '90', 'Oloroso Sherry Casks', '1'),
    ('Old Forester', 'Straight Rye Whiskey','', '', '', '', 'Rye', 'Small Batch', '', '', '100', '', '1'),
    ('Blue Run', 'Emerald Rye Whiskey','', '', '', '', 'Rye', 'Unknown', '', '', '116.7', '', '1'),
    ('Bardstown Bourbon Company', 'Collaboration Series Foursquare Rum','', '', '', '', 'Bourbon', 'Small Batch', '', '', '107', 'Rum Barrels', '1'),
    ('Jack Daniel''s', 'Heritage Series Twice Barreled Rye','', '', '', '', 'Rye', 'Small Batch', '2023', '', '100', '', '1'),
    ('Old Forester', '1924 10 Year Old','', '', '', '', 'Bourbon', 'Small Batch', '', '', '100', '', '1'),
    ('Heaven Hill', 'Parker''s Heritage 10 Year Rye','', '', '', '', 'Rye', 'Small Batch', '', '10y', '128.8', '', '1'),
    ('Wild Turkey', 'Russel''s Reserve','22-0671', 'Bruce Rusel for Ernie''s', '', '', 'Bourbon', 'Single Barrel', '', '9y', '110', '', '1'),
    ('Buffalo Trace Distillery', 'Weller Special Reserve 1.75L','', '', '', '', 'Bourbon', 'Small Batch', '', '', '90', '', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', 'BC Liquor Stores', 'K', '5', 'Bourbon', 'Single Barrel', '', '', '126.4', '', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', 'Cox''s & Evergreen Liquors', 'G', '4', 'Bourbon', 'Single Barrel', '', '', '127.6', '', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', 'Little Family Selection', 'K', '7', 'Bourbon', 'Single Barrel', '', '', '130.1', '', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', 'Barrel #6379 for SFWTC', 'L', '3', 'Bourbon', 'Single Barrel', '', '', '131.5', '', '1'),
    ('Jos. A. Magnus & Co.', 'Joseph Magnus','', '', '', '', 'Bourbon', 'Small Batch', '181', '', '100', 'Sherry and Cognac Casks', '1'),
    ('Blaum Bros', 'Oldfangled Knotter Bourbon','', '', '', '', 'Bourbon', 'Single Barrel', '', '12y', '106.6', '', '1'),
    ('Blaum Bros', 'Straight Rye Whiskey','', 'April Foolz', '', '', 'Rye', 'Single Barrel', '', '8yr', '135', '', '1'),
    ('Heaven Hill', 'Elijah Craig Barrel Proof','', '', '', '', 'Bourbon', 'Small Batch', 'C923', '13y7m', '133', '', '1'),
    ('Heaven Hill', 'Elijah Craig Barrel Proof','', 'Lady''s Liquor', '', '', 'Bourbon', 'Single Barrel', '', '8y', '131.8', '', '1'),
    ('Heaven Hill', 'Elijah Craig Barrel Proof','', '', '', '', 'Bourbon', 'Small Batch', 'C919', '12y', '136.8', '', '1'),
    ('Penelope', 'Toasted Barrel Strength','', '', '', '', 'Bourbon', 'Small Batch', '22-01', '4y', '114', 'Toasted Barrels', '1'),
    ('High West', 'A Midwinter Nights Dram','', '', '', '', 'Rye', 'Small Batch', 'Act 9 Scene 4', '', '98.6', 'French Oak Port Barrels', '1'),
    ('Beast Master''s Club', 'Straight Rye Whiskey','11', '', '', '', 'Rye', 'Single Barrel', '', '8y', '132.6', '', '1'),
    ('Old Forester', 'Old Forester Single Barrel Barrel Strength','', 'ShopRite Selection 2020', 'G', '7', 'Bourbon', 'Single Barrel', '', '', '131.7', '', '1'),
    ('Cardhu Gold Reserve', 'House Targaryen','', '', '', '', 'Single Malt Scotch', 'Special Release', '', '', '80', '', '2'),
    ('Oban Bay Reserve', 'The Night''s Watch','', '', '', '', 'Single Malt Scotch', 'Special Release', '', '', '86', '', '1'),
    ('Mortlach', 'Six Kingdoms','', '', '', '', 'Single Malt Scotch', 'Special Release', '', '15y', '92', '', '1'),
    ('Talisker', 'House Greyjoy','', '', '', '', 'Single Malt Scotch', 'Special Release', '', '', '91.6', '', '1'),
    ('Glendullan', 'House Tully','', '', '', '', 'Single Malt Scotch', 'Special Release', '', '', '80', '', '2'),
    ('Lagavulin', 'House Lannister','', '', '', '', 'Single Malt Scotch', 'Special Release', '', '9y', '92', '', '2'),
    ('Royal Lochnagar', 'House Baratheon','', '', '', '', 'Single Malt Scotch', 'Special Release', '', '12y', '80', '', '1'),
    ('Clynelish', 'House Tyrell','', '', '', '', 'Single Malt Scotch', 'Special Release', '', '', '102.4', '', '1'),
    ('Dalwhinnie', 'House Stark','', '', '', '', 'Single Malt Scotch', 'Special Release', '', '', '86', '', '2'),
    ('Jim Beam', 'Little Book ','', '', '', '', 'Bourbon', 'Special Release', 'Chapter 1', '', '128.2', '', '1'),
    ('Jim Beam', 'Little Book ','', '', '', '', 'Bourbon', 'Special Release', 'Chapter 2', '', '118.8', '', ''),
    ('Jim Beam', 'Little Book ','', '', '', '', 'Bourbon', 'Special Release', 'Chapter 4', '', '122.8', '', ''),
    ('Jim Beam', 'Little Book ','', '', '', '', 'Bourbon', 'Special Release', 'Chapter 5', '', '116.8', '', ''),
    ('Jim Beam', 'Lineage','', '', '', '', 'Bourbon', 'Special Release', '', '15y', '111', '', ''),
    ('Buffalo Trace Distillery', 'Stagg','', '', '', '', 'Bourbon', 'Small Batch', '23B', '', '127.8', '', '0'),
    ('Buffalo Trace Distillery', 'Stagg','', '', '', '', 'Bourbon', 'Small Batch', '23C', '', '125.9', '', '1'),
    ('W.B Saffel', 'Straight Bourbon Whiskey','', '', '', '', 'Bourbon', 'Small Batch', 'Batch 1', '', '107', '', '1'),
    ('Boone County', 'Bourbon','BCB21', 'Gallenstein Selection #9', '', '', 'Bourbon', 'Single Barrel', '', '6y', '110.8', '', '1'),
    ('Buffalo Trace Distillery', 'Blanton''s','220', '', 'H', '', 'Bourbon', 'Single Barrel', '', '', '93', '', '1'),
    ('Macallan', 'The Macallan','', '', '', '', 'Single Malt Scotch', 'Small Batch', '', '12y', '86', 'Sherry Oak Cask', '1'),
    ('Lagavulin', 'Lagavulin 16','', '', '', '', 'Single Malt Scotch', 'Small Batch', '', '16y', '86', '', '1'),
    ('Balvenie', 'Portwood 21','', '', '', '', 'Single Malt Scotch', 'Small Batch', '', '21y', '86', 'Portwood Casks', '1'),
    ('Glenmorangie', 'The Original Glenmorangie','', '', '', '', 'Single Malt Scotch', 'Small Batch', '', '10y', '86', '', '1'),
    ('Ardbeg', 'Ardbeg an OA','', '', '', '', 'Single Malt Scotch', 'Small Batch', '', '', '93.1', '', '1'),
    ('Lagavulin', 'The Distiller''s Edition','', '', '', '', 'Single Malt Scotch', 'Small Batch', '', '16y', '86', '', '1'),
    ('Macallan', 'Rare Cask','', '', '', '', 'Single Malt Scotch', 'Small Batch', 'Batch 2', '', '86', '', '1'),
    ('Lucky Seven', 'The Hold Up','', '', '', '', 'Bourbon', 'Small Batch', 'Batch 8', '9y', '100', '', '1'),
    ('Lucky Seven', 'The Proprietor','19', '', '', '', 'Bourbon', 'Single Barrel', '', '14y', '118', '', '1'),
    ('Calumet Farm', 'Small Batch','', '', '', '', 'Bourbon', 'Small Batch', 'CA8Y03', '8y', '90', '', '1'),
    ('Johnnie Walker', 'A Song of Fire','', '', '', '', 'Blended Scotch', 'Small Batch', '', '', '81.6', '', '1'),
    ('Woodford Reserve', 'Kentucky Derby 150th','', '', '', '', 'Bourbon', 'Small Batch', '', '', '90.4', '', '1'),
    ('Bardstown Bourbon Company', 'Triple Blended Stave Finish','', '', '', '', 'Bourbon', 'Special Release', '', '', '109', '', '1'),
    ('Bardstown Bourbon Company', 'Discovery Series','', '', '', '', 'Bourbon', 'Special Release', 'Serries 11', '', '118.1', '', '1'),
    ('Jura', 'Jura','', '', '', '', 'Single Malt Scotch', 'Small Batch', '', '10y', '80', '', '1'),
    ('Barton', '1792  Full Proof','', 'Lynnway Liquors Barrel #3', '', '', 'Bourbon', 'Single Barrel', '', '', '125', '', '0'),
    ('Barton', '1792 Full Proof','', 'Colonial Wine & Spirits', '', '', 'Bourbon', 'Single Barrel', '', '', '125', '', '1'),
    ('Heaven Hill', 'Elijah Craig Toasted Barrel','', '', '', '', 'Bourbon', 'Small Batch', '', '', '94', 'Toasted New Oak Barrels', '1'),
    ('Heaven Hill', 'Elijah Craig Small Batch','', '', '', '', 'Bourbon', 'Small Batch', '', '', '94', '', '1'),
    ('Buffalo Trace Distillery', 'Elmer T. Lee','', '', '', '', 'Bourbon', 'Single Barrel', '', '', '90', '', '1'),
    ('Bull Run', 'Straight Bourbon Whiskey','', '', '', '', 'Bourbon', 'Small Batch', '', '10y', '109.22', 'Cognac Casks', '1'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','83', 'Whiskey and Wishes', '', '', 'Rye', 'Single Barrel', '', '7y', '116.14', '', '1'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','130', 'Ryeday The13th', '', '', 'Rye', 'Single Barrel', '', '7y', '113', '', '1'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','23', 'Leap Day', '', '', 'Rye', 'Single Barrel', '', '7y', '112.8', '', '1'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','162', 'RyeQuil', '', '', 'Rye', 'Single Barrel', '', '8y', '115.84', '', '2'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','151', 'If You Ain''t First You''re Last', '', '', 'Rye', 'Single Barrel', '', '8y', '115.3', '', '1'),
    ('Nashville Barrel Company', 'Straight Rye Whiskey','30', 'Bourbon World', '', '', 'Rye', 'Single Barrel', '', '8y', '110.4', '', '1'),
    ('Smooth Ambler', 'Old Scout','', 'Ryes Of The Bourbon Guys Part Three', '', '', 'Rye', 'Single Barrel', '', '6y', '115.6', '', '1'),
    ('Starlight', 'Indiana Straight Rye Whiskey','17239', 'The Bourbon Guys', '', '', 'Rye', 'Single Barrel', '', '4y', '110.6', '', '1'),
    ('M&O Spirits', 'Smoke','11', '', '', '', 'American Whiskey', 'Small Batch', '', '', '100', '', '1'),
    ('Proof & Wood Ventures', 'The Representative','', '', '', '', 'Bourbon', 'Small Batch', '', '4y', '115.32', '', '1'),
    ('Kirkland', 'Speyside Single Malt Scotch Whisky','', '', '', '', 'Single Malt Scotch', 'Small Batch', '', '23y', '92', '', '1'),
    ('Kentucky Artisan Distillery', 'Pinhook','', '', '', '', 'Bourbon', 'Small Batch', '', '7y', '115', '', '1'),
    ('Kentucky Artisan Distillery', 'Pinhook','', '', '', '', 'Bourbon', 'Small Batch', '', '8y', '114.6', '', '2'),
    ('New Riff', 'Kentucky Straight Bourbon','', '', '', '', 'Bourbon', 'Small Batch', '', '8y', '100', '', '1'),
    ('Jim Beam', 'Booker''s','', '', '', '', 'Bourbon', 'Small Batch', '44986', '7y1m', '126.6', '', '1'),
    ('Traverse City Whiskey Co.', 'Straight Wheat Whiskey','', 'Opa Wheat 2023', '', '', 'Wheat Whiskey', 'Single Barrel', '', '5y', '115', '', '1'),
    ('Maker''s Mark', 'Private Selection','', 'Collect Call from Chay', '', '', 'Bourbon', 'Single Barrel', '', '', '110.3', 'Stave Finish', '1'),
    ('Wenzel Whiskey', 'Wheated 3','', '', '', '', 'Wheat Whiskey', 'Small Batch', '', '', '112.4', '', '1'),
    ('Wenzel Whiskey', 'Straight Bourbon Whiskey','', 'Kismet', '', '', 'Bourbon', 'Small Batch', '', '', '114.76', '', '1'),
    ('Ross & Squibb Distillery', 'Rossville Union','1202', 'All Rye All Rye', '', '', 'Rye', 'Single Barrel', '', '', '112.2', '', '1'),
    ('Starlight', 'Double Oaked Rye','', 'The Party Source', '', '', 'Rye', 'Small Batch', '23-2146-1', '4y', '116.8', '', '1'),
    ('Lawrenceburg Bourbon Company', 'High Wheat Rye Whiskey','2', '', '', '', 'Rye', 'Single Barrel', '', '7y', '117.8', 'Double Oak', '1'),
    ('Buffalo Trace Distillery', 'Weller Antique 107','83A', 'The Sting', '', '', 'Wheated Bourbon', 'Single Barrel', '', '', '107', '', '2'),
    ('Heaven Hill', 'Bottled-In-Bond','', '', '', '', 'Bourbon', 'Small Batch', '', '7y', '100', '', '1'),
    ('Wild Turkey', '12 Year Bourbon','', '', '', '', 'Bourbon', 'Small Batch', '', '12y', '101', '', '1'),
    ('O.K.I.', 'Reserve','', '', '', '', 'American Whiskey', 'Small Batch', 'Batch 1', '', '100', '', '1'),
    ('Wild Turkey', 'Kentucky Spirit','2968', '', 'A', '', 'Bourbon', 'Single Barrel', '', '', '101', '', '1'),
    ('Wild Turkey', 'Russel''s Reserve','21-0120', 'Kroger Wine & Spirits', 'K', '4', 'Bourbon', 'Single Barrel', '', '9y', '110', '', '1'),
    ('Jim Beam', 'Knob Creek Single Barrel Reserve','', '', '', '', 'Bourbon', 'Single Barrel', '', '9y', '120', '', '1'),
    ('Willett', 'Noah''s Mill','', '', '', '', 'Bourbon', 'Small Batch', '', '', '114.3', '', '1'),
    ('Sagamore Spirits', 'Double Oak Rye','', '', '', '', 'Rye', 'Small Batch', '7AD', '', '96.6', 'Double Oak', '1'),
    ('Heaven Hill', 'Larceny Barrel Proof','', '', '', '', 'Bourbon', 'Small Batch', 'B523', '', '124.4', '', '1'),
    ('Jim Beam', 'Knob Creek Single Barrel Select','', 'Cox''s Evergreen Liquors', '1', '3', 'Bourbon', 'Single Barrel', '', '9y', '120', '', '1'),
    ('Michter''s', 'Shenk''s Homestead','', '', '', '', 'Bourbon', 'Small Batch', 'L20G1521', '', '91.2', '', '1'),
    ('Watershed', 'Uncut Unfiltered','', '', '', '', 'Bourbon', 'Small Batch', 'Batch #001', '4y', '126.8', '', '1'),
    ('Barrell', 'Bourbon','', '', '', '', 'Bourbon', 'Small Batch', 'Batch #034', '6y', '114.62', '', '1'),
    ('Alberta Premium', 'Cask Strength Rye','', '', '', '', 'Rye', 'Limited Edition', '', '', '127.4', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof','', '', '', '', 'Tennessee Whiskey', 'Single Barrel', '', '', '133.4', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', 'Total Wine & More', '', '', 'Rye', 'Single Barrel', '', '', '129.9', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '136.3', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '130.2', '', '1'),
    ('Barrel King', 'Knighted','', '', '', '', 'Bourbon', 'Small Batch', 'Batch #081', '', '112.2', 'Rare Ex-Bourbon Barrels', '1'),
    ('Four Roses', 'Private Selection OBSV','87-2s', 'Cask', 'SN', '2', 'Bourbon', 'Single Barrel', '', '9y10m', '111.6', '', '1'),
    ('Four Roses', 'Private Selection OESF','15-1P', 'Buy-Rite Select', 'SS', '1', 'Bourbon', 'Single Barrel', '', '10y10m', '101.4', '', '1'),
    ('Four Roses', 'Private Selection OBSK','88-6C', 'Hotel Covington', 'QS', '6', 'Bourbon', 'Single Barrel', '', '8y9m', '125.2', '', '1'),
    ('Four Roses', 'Private Selection OBSQ','24-6N', 'Binny''s', 'RS', '6', 'Bourbon', 'Single Barrel', '', '10y2m', '128.6', '', '1'),
    ('Buffalo Trace Distillery', 'Benchmark Full Proof','', '', '', '', 'Bourbon', 'Small Batch', '', '', '125', '', '1'),
    ('Boone County', 'Wheated Bourbon','', 'Ohio Liquor Selection #1', '', '', 'Bourbon', 'Single Barrel', '', '7y', '121', '', '1'),
    ('Boone County', 'Wheated Bourbon','', 'Ohio Liquor Selection #1', '', '', 'Bourbon', 'Single Barrel', '', '7y', '120.7', '', '1'),
    ('Remus', 'Remus Repeal Reserve','', '', '', '', 'Bourbon', 'Small Batch', 'Batch #005', '', '100', '', '1'),
    ('Remus', 'Remus Repeal Reserve','', '', '', '', 'Bourbon', 'Small Batch', 'Batch #006', '', '100', '', '1'),
    ('Remus', 'Remus Repeal Reserve','', '', '', '', 'Bourbon', 'Small Batch', 'Batch #002', '', '100', '', '1'),
    ('J. Mattingly', 'Pretty Rye For A White Guy','', '', '', '', 'Rye', 'Small Batch', '', '', '117', '', '1'),
    ('J. Mattingly', 'mr. bRYEtside','', '', '', '', 'Rye', 'Small Batch', '', '', '115', '', '1'),
    ('J. Mattingly', 'Doink Monster','', '', '', '', 'Bourbon', 'Small Batch', '', '', '112', '', '2'),
    ('J. Mattingly', 'Not My Dong','', '', '', '', 'Bourbon', 'Small Batch', '', '', '114', '', '1'),
    ('Middle West Spirits', 'Dark Pumpernickel Rye','', 'Brothermania', '', '', 'Rye', 'Single Barrel', '', '5y', '126.22', '', '1'),
    ('Proof & Wood Ventures', 'Tubmlin Dice Straight Rye Whiskey','', '', '', '', 'Rye', 'Small Batch', '', '8y', '116.4', '', '1'),
    ('Jim Beam', 'Old Grand-Dad 114','', '', '', '', 'Bourbon', 'Small Batch', '', '', '114', '', '1'),
    ('Buffalo Trace Distillery', 'Buffalo Trace','', 'Stagecoach Liquor', '', '', 'Bourbon', 'Single Barrel', '', '', '90', '', '1'),
    ('Buffalo Trace Distillery', 'Buffalo Trace','', '', '', '', 'Bourbon', 'Small Batch', '', '', '90', '', '1'),
    ('Buffalo Trace Distillery', 'Buffalo Trace','', 'Kings Wine and Spirits', '', '', 'Bourbon', 'Single Barrel', '', '', '90', '', '1'),
    ('Proof & Wood Ventures', 'The Senator','', '', '', '', 'Rye', 'Single Barrel', '', '6y', '114.22', '', '1'),
    ('Ringside Whiskey', 'Buster Douglas','', '', '', '', 'Bourbon', 'Small Batch', '', '', '84', '', '1'),
    ('Jim Beam', 'Jim Beam Black 7 Year','', '', '', '', 'Bourbon', 'Small Batch', '', '7y', '90', '', '1'),
    ('Buffalo Trace Distillery', 'E.H. Taylor Barrel Proof','', '', '', '', 'Bourbon', 'Small Batch', '', '', '131.1', '', '1'),
    ('Angel''s Envy', 'Cask Strength Rye','', '', '', '', 'Rye', 'Small Batch', '2023', '', '114.4', 'Sauternes Desert Wine Barrels and Toasted Oak', '1'),
    ('Jim Beam', 'Hardin''s Creek','', '', '', '', 'Bourbon', 'Small Batch', 'Boston', '17y', '110', '', '1'),
    ('Jim Beam', 'Hardin''s Creek','', '', '', '', 'Bourbon', 'Small Batch', 'Frankfurt', '17y', '110', '', '1'),
    ('O.K.I.', 'Straight Bourbon Whiskey','', 'Prohibition', '', '', 'Bourbon', 'Single Barrel', '', '6y', '116.4', '', '1'),
    ('O.K.I.', 'Straight Bourbon Whiskey','', 'The Fred Minnick Show', '', '', 'Bourbon', 'Single Barrel', '', '6y', '123.2', '', '1'),
    ('O.K.I.', 'Straight Rye Whiskey','', '', '', '', 'Rye', 'Single Barrel', '', '6y', '120.4', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '129.9', '', '2'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '133.1', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '127.8', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '134.5', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '132.6', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '129.1', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '134.3', '', '1'),
    ('Jack Daniel''s', 'Single Barrel Barrel Proof Rye','', '', '', '', 'Rye', 'Single Barrel', '', '', '131.4', '', '1'),
    ('Jack Daniel''s', '10 Year','', '', '', '', 'Tennessee Whiskey', 'Small Batch', 'Batch #002', '', '97', '', '1'),
    ('Jack Daniel''s', '12 Year','', '', '', '', 'Tennessee Whiskey', 'Small Batch', 'Batch #001', '', '107', '', '1'),
    ('Old Elk', 'Rum Cask Finished Rye','1013', 'Whiskey Pirates', '', '', 'Rye', 'Single Barrel', '', '6y', '119.6', '', '1'),
    ('Ross & Squibb Distillery', 'Remus Straight Bourbon Whiskey','743', 'OpaFenders', '', '', 'Bourbon', 'Single Barrel', '', '', '113.2', '', '1'),
    ('Barton', '1792 Full Proof','', 'The A Team', '', '', 'Bourbon', 'Single Barrel', '', '', '125', '', '1'),
    ('Western Reserve', 'Rye','', 'No Tags, Says Who?', '', '', 'Rye', 'Single Barrel', '', '18y', '100', 'Rum Casks', '1'),
    ('Wild Turkey', 'Russel''s Reserver','', 'Turkey Tales', 'K', '4', 'Bourbon', 'Single Barrel', '', '10y', '110', '', '1'),
    ('Wild Turkey', 'Russel''s Reserver','', 'Cancer Sucks', 'TY-Q', '4', 'Bourbon', 'Single Barrel', '', '8y', '110', '', '1'),
    ('O.K.I.', 'Straight Bourbon Whiskey','251', 'Highlander', '', '', 'Bourbon', 'Single Barrel', '', '7y', '114.1', '', '1'),
    ('O.K.I.', 'Straight Rye Whiskey','110', 'It''s OK To Rye', '', '', 'Rye', 'Single Barrel', '', '6y', '116', '', '1'),
    ('Jim Beam', 'Knob Creek Single Barrel Bourbon','', 'That''s Amore', 'P', '5', 'Bourbon', 'Single Barrel', '', '10y', '120', '', '1'),
    ('Jim Beam', 'Knob Creek Single Barrel Bourbon','', 'A Is For Alcohol', 'X', '3', 'Bourbon', 'Single Barrel', '', '9y', '120', '', '1'),
    ('Jim Beam', 'Knob Creek Single Barrel Bourbon','', 'Fred(die)''s Knoew', 'P', '4', 'Bourbon', 'Single Barrel', '', '10y', '120', '', '1'),
    ('Jim Beam', 'Knob Creek Single Barrel Bourbon','', 'Buckeye Bourbon Barrel #5', 'G', '3', 'Bourbon', 'Single Barrel', '', '9y', '120', '', '1'),
    ('Jim Beam', 'Knob Creek Single Barrel Bourbon','', 'Up Your Penninsula', 'I', '4', 'Bourbon', 'Single Barrel', '', '8y', '120', '', '1'),
    ('Jim Beam', 'Knob Creek Single Barrel Bourbon','', 'You Matter #3', 'N', '6', 'Bourbon', 'Single Barrel', '', '9y', '120', '', '1'),
    ('Smooth Ambler', 'Old Scout','', 'C-Rye Me a River', '', '', 'Rye', 'Single Barrel', '', '5y', '116.22', '', '1'),
    ('Buzzard''s Roost', 'Straight Rye Whiskey','22-51211', 'Rye Choose One', '', '', 'Rye', 'Single Barrel', '', '', '116.2', '', '1'),
    ('New Riff', 'Single Barrel Rye','10716', 'Riff-mas In July', '', '', 'Rye', 'Single Barrel', '', '4y', '108.2', '', '1'),
    ('Lux Row', 'Rebel Distiller''s Collection','8119551', 'Bee''s Knees', '', '', 'Bourbon', 'Single Barrel', '', '', '113', '', '1'),
    ('Heaven''s Door', 'Straight Bourbon Whiskey','27898', 'C Shen Maria', '', '', 'Bourbon', 'Single Barrel', '', '', '125.1', '', '1'),
    ('Heaven Hill', 'Elijah Craig Barrel Proof','6305023', 'Better Late Than Never', '', '', 'Bourbon', 'Single Barrel', '', '', '127.1', '', '1'),
    ('Traverse City Whiskey Co.', 'Straight Rye Whiskey','', 'Opa 2023', '', '', 'Rye', 'Single Barrel', '', '7y', '123.4', '', '1'),
    ('Heaven''s Door', 'Straight Bourbon Whiskey','21590', 'Knock Knock', '', '', 'Bourbon', 'Single Barrel', '', '', '120.3', '', '1'),
    ('Backbone Bourbon', 'Straight Bourbon Whiskey','', 'Justin''s House of Bourbon', '', '', 'Bourbon', 'Single Barrel', '', '8y', '117.4', '', '1'),
    ('Barrell', 'Bourbon','2602', 'Rural Inn: Vince''s Pick', '', '', 'Bourbon', 'Single Barrel', '', '9y7mo', '119', '', '1'),
    ('M&O Spirits', 'Batch 27','9', 'Smokin'' in the COW''s Room', '', '', 'Bourbon', 'Single Barrel', '', '', '123.7', 'Double Oaked', '1')
) as t ([Distillery], [Label], [Barrel], [SingleBarrelName], [Warehouse], [Floor], [WhiskeyType], [ReleaseType], [Release], [AgeStatement], [Proof], [Finish], [Quantity])

INSERT INTO [Bottles] ([Name], [ReleaseTypeId], [DistilleryId], [Proof], [AgeYears], [AgeMonths])
SELECT 
    tb.[Label], 
    rt.[ReleaseTypeId], 
    d.[DistilleryId], 
    tb.[Proof],
    CASE 
        WHEN CHARINDEX('y', [AgeStatement]) = 0 THEN 0
        ELSE SUBSTRING([AgeStatement], 1, CHARINDEX('y', [AgeStatement]) - 1)
    END AS [AgeYears],
    CASE
        WHEN CHARINDEX('y', [AgeStatement]) = 0 OR CHARINDEX('m', [AgeStatement]) = 0 THEN 0
        ELSE SUBSTRING([AgeStatement], CHARINDEX('y', [AgeStatement]) + 1, (CHARINDEX('m', [AgeStatement]) - CHARINDEX('y', [AgeStatement]) - 1))
    END AS [AgeMonths]

FROM #TempBottles tb
LEFT JOIN [ReleaseTypes] rt ON tb.ReleaseType = rt.Name
LEFT JOIN [Distilleries] d ON tb.Distillery = d.Name

