DROP TABLE IF EXISTS #TempDistilleries

SELECT * INTO #TempDistilleries FROM
(
    VALUES
    ('Heaven Hill', 'KY'),
    ('Cat''s Eye Distillery', 'IA'),
    ('Calumet Farm', 'KY'),
    ('Wild Turkey', 'KY'),
    ('Jack Daniel''s', 'TN'),
    ('Angel''s Envy', 'KY'),
    ('Bull Run', 'OR'),
    ('Old Forester', 'KY'),
    ('Augusta', 'KY'),
    ('2XO', 'KY'),
    ('Nashville Barrel Company', 'TN'),
    ('Jersey Artisan Distilling', 'NJ'),
    ('Sagamore Spirits', 'MD'),
    ('Middle West Spirits', 'OH'),
    ('Proof & Wood Ventures', 'KY'),
    ('Traverse City Whiskey Co.', 'MI'),
    ('Triple Down', 'IN'),
    ('Early Times', 'KY'),
    ('Tincup', 'CO'),
    ('Holladay Distillery', 'MO'),
    ('Whiskey Theif Distillery', 'KY'),
    ('Buffalo Trace Distillery', 'KY'),
    ('Lux Row', 'KY'),
    ('Bardstown Bourbon Company', 'KY'),
    ('Four Roses', 'KY'),
    ('Penelope', 'NJ'),
    ('Blackout Group', 'KY'),
    ('High West', 'UT'),
    ('Blaum Bros', 'KY'),
    ('Orphan Barrel', 'TN'),
    ('Sixth Street', 'TX'),
    ('Woodford Reserve', 'KY'),
    ('Watershed', 'OH'),
    ('Blue Run', 'KY'),
    ('Jos. A. Magnus & Co.', 'DC'),
    ('Beast Master''s Club', 'NY'),
    ('Cardhu Gold Reserve', '--'),
    ('Oban Bay Reserve', '--'),
    ('Mortlach', '--'),
    ('Talisker', '--'),
    ('Glendullan', '--'),
    ('Lagavulin', '--'),
    ('Royal Lochnagar', '--'),
    ('Clynelish', '--'),
    ('Dalwhinnie', '--'),
    ('Jim Beam', 'KY'),
    ('W.B Saffel', 'KY'),
    ('Boone County', 'KY'),
    ('Macallan', '--'),
    ('Balvenie', '--'),
    ('Glenmorangie', '--'),
    ('Ardbeg', '--'),
    ('Lucky Seven', 'KY'),
    ('Johnnie Walker', '--'),
    ('Jura', '--'),
    ('Barton', 'KY'),
    ('Smooth Ambler', 'WV'),
    ('Starlight', 'IN'),
    ('M&O Spirits', 'OH'),
    ('Kirkland', '-- '),
    ('Kentucky Artisan Distillery', 'KY'),
    ('New Riff', 'KY'),
    ('Maker''s Mark', 'KY'),
    ('Wenzel Whiskey', 'KY'),
    ('Ross & Squibb Distillery', 'IN'),
    ('Lawrenceburg Bourbon Company', 'KY'),
    ('O.K.I.', 'KY'),
    ('Willett', 'KY'),
    ('Michter''s', 'KY'),
    ('Barrell', 'KY'),
    ('Alberta Premium', 'AB'),
    ('Barrel King', 'MO'),
    ('Remus', 'IN'),
    ('J. Mattingly', 'KY'),
    ('Ringside Whiskey', 'OH'),
    ('Old Elk', 'CO'),
    ('Western Reserve', 'OH'),
    ('Buzzard''s Roost', 'KY'),
    ('Heaven''s Door', 'IL'),
    ('Backbone Bourbon', 'IN')
) as t ([Name], [StateProvince])

INSERT INTO [Distilleries] ([Name], [StateProvince])
SELECT td.[Name], s.[StateProvince] 
FROM #TempDistilleries td 